# Generated by Django 3.0.3 on 2020-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreatedevent',
            name='post_content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='postupdatedevent',
            name='post_content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
