# Generated by Django 3.0.3 on 2020-03-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_siteuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='image',
            field=models.ImageField(default='cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png', upload_to='profile-images/'),
        ),
    ]
