# Generated by Django 3.0.3 on 2020-03-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200326_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='image',
            field=models.CharField(default='http://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png', max_length=2048),
        ),
    ]
