# Generated by Django 3.0.3 on 2020-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200327_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.UUIDField()),
                ('votee', models.UUIDField()),
                ('post', models.UUIDField()),
                ('vote', models.IntegerField(max_length=1)),
            ],
        ),
    ]
