# Generated by Django 3.0.3 on 2020-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_elotracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elotracker',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
