# Generated by Django 3.0.3 on 2020-02-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCreatedEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Event')),
                ('user_id', models.UUIDField()),
                ('post_id', models.UUIDField()),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('content', models.CharField(max_length=10000)),
            ],
            bases=('event.event',),
        ),
        migrations.CreateModel(
            name='CommentDeletedEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Event')),
                ('comment_id', models.UUIDField()),
            ],
            bases=('event.event',),
        ),
        migrations.CreateModel(
            name='CommentUpdatedEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Event')),
                ('comment_id', models.UUIDField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('post_id', models.UUIDField(blank=True, null=True)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            bases=('event.event',),
        ),
    ]
