# Generated by Django 3.0.3 on 2020-04-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('U', 'User'), ('P', 'Post'), ('E', 'Establishment')], default='u', max_length=1),
            preserve_default=False,
        ),
    ]
