# Generated by Django 3.0.3 on 2020-03-11 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('establishment_id', models.UUIDField(default=uuid.UUID('b3fa4f09-2b52-48e2-8fed-895d28b46a04'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
