# Generated by Django 3.0.3 on 2020-03-11 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_auto_20200311_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='establishment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
