# Generated by Django 3.0.3 on 2020-03-12 19:20

from django.db import migrations, models
import establishments.models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_auto_20200311_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='flag_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='rating',
            field=models.IntegerField(default=0, validators=[establishments.models.validate_less_than_10]),
        ),
    ]
