# Generated by Django 3.0.3 on 2020-03-26 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import establishments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0005_auto_20200312_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='flag_counter',
        ),
        migrations.AlterField(
            model_name='establishment',
            name='rating',
            field=models.FloatField(default=0, validators=[establishments.models.validate_less_than_10]),
        ),
        migrations.CreateModel(
            name='Flag_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.Establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
