# Generated by Django 3.0.3 on 2020-03-26 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0006_auto_20200326_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='establishment',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
